# Generated by Django 4.0.4 on 2022-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_studentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDetails',
        ),
        migrations.AddField(
            model_name='student',
            name='Description',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
