# Generated by Django 4.0.4 on 2022-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
